contact_links:
  - name: Ask a question
    about: Ask questions and discuss with other users of the library.
    url: https://github.com/EnokiUN/pyvolt/discussions
  - name: Revolt Server
    about: Use our official Revolt server to ask for help and questions as well.
    url: https://rvlt.gg/bwtscg1F
